// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steammessages_clientserver_2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientGetDepotDecryptionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepotId       *uint32                `protobuf:"varint,1,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	AppId         *uint32                `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientGetDepotDecryptionKey) Reset() {
	*x = CMsgClientGetDepotDecryptionKey{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientGetDepotDecryptionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientGetDepotDecryptionKey) ProtoMessage() {}

func (x *CMsgClientGetDepotDecryptionKey) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientGetDepotDecryptionKey.ProtoReflect.Descriptor instead.
func (*CMsgClientGetDepotDecryptionKey) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientGetDepotDecryptionKey) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *CMsgClientGetDepotDecryptionKey) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type CMsgClientGetDepotDecryptionKeyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Eresult            *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	DepotId            *uint32                `protobuf:"varint,2,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	DepotEncryptionKey []byte                 `protobuf:"bytes,3,opt,name=depot_encryption_key,json=depotEncryptionKey" json:"depot_encryption_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CMsgClientGetDepotDecryptionKeyResponse fields.
const (
	Default_CMsgClientGetDepotDecryptionKeyResponse_Eresult = int32(2)
)

func (x *CMsgClientGetDepotDecryptionKeyResponse) Reset() {
	*x = CMsgClientGetDepotDecryptionKeyResponse{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientGetDepotDecryptionKeyResponse) ProtoMessage() {}

func (x *CMsgClientGetDepotDecryptionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientGetDepotDecryptionKeyResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientGetDepotDecryptionKeyResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientGetDepotDecryptionKeyResponse_Eresult
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) GetDepotId() uint32 {
	if x != nil && x.DepotId != nil {
		return *x.DepotId
	}
	return 0
}

func (x *CMsgClientGetDepotDecryptionKeyResponse) GetDepotEncryptionKey() []byte {
	if x != nil {
		return x.DepotEncryptionKey
	}
	return nil
}

type CMsgClientCheckAppBetaPassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Betapassword  *string                `protobuf:"bytes,2,opt,name=betapassword" json:"betapassword,omitempty"`
	Language      *int32                 `protobuf:"varint,3,opt,name=language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientCheckAppBetaPassword) Reset() {
	*x = CMsgClientCheckAppBetaPassword{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientCheckAppBetaPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientCheckAppBetaPassword) ProtoMessage() {}

func (x *CMsgClientCheckAppBetaPassword) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientCheckAppBetaPassword.ProtoReflect.Descriptor instead.
func (*CMsgClientCheckAppBetaPassword) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgClientCheckAppBetaPassword) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientCheckAppBetaPassword) GetBetapassword() string {
	if x != nil && x.Betapassword != nil {
		return *x.Betapassword
	}
	return ""
}

func (x *CMsgClientCheckAppBetaPassword) GetLanguage() int32 {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return 0
}

type CMsgClientCheckAppBetaPasswordResponse struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	Eresult       *int32                                                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	Betapasswords []*CMsgClientCheckAppBetaPasswordResponse_BetaPassword `protobuf:"bytes,4,rep,name=betapasswords" json:"betapasswords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientCheckAppBetaPasswordResponse fields.
const (
	Default_CMsgClientCheckAppBetaPasswordResponse_Eresult = int32(2)
)

func (x *CMsgClientCheckAppBetaPasswordResponse) Reset() {
	*x = CMsgClientCheckAppBetaPasswordResponse{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientCheckAppBetaPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientCheckAppBetaPasswordResponse) ProtoMessage() {}

func (x *CMsgClientCheckAppBetaPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientCheckAppBetaPasswordResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientCheckAppBetaPasswordResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgClientCheckAppBetaPasswordResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientCheckAppBetaPasswordResponse_Eresult
}

func (x *CMsgClientCheckAppBetaPasswordResponse) GetBetapasswords() []*CMsgClientCheckAppBetaPasswordResponse_BetaPassword {
	if x != nil {
		return x.Betapasswords
	}
	return nil
}

type CMsgClientCheckAppBetaPasswordResponse_BetaPassword struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Betaname        *string                `protobuf:"bytes,1,opt,name=betaname" json:"betaname,omitempty"`
	Betapassword    *string                `protobuf:"bytes,2,opt,name=betapassword" json:"betapassword,omitempty"`
	Betadescription *string                `protobuf:"bytes,3,opt,name=betadescription" json:"betadescription,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CMsgClientCheckAppBetaPasswordResponse_BetaPassword) Reset() {
	*x = CMsgClientCheckAppBetaPasswordResponse_BetaPassword{}
	mi := &file_steammessages_clientserver_2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientCheckAppBetaPasswordResponse_BetaPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientCheckAppBetaPasswordResponse_BetaPassword) ProtoMessage() {}

func (x *CMsgClientCheckAppBetaPasswordResponse_BetaPassword) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientCheckAppBetaPasswordResponse_BetaPassword.ProtoReflect.Descriptor instead.
func (*CMsgClientCheckAppBetaPasswordResponse_BetaPassword) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_2_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CMsgClientCheckAppBetaPasswordResponse_BetaPassword) GetBetaname() string {
	if x != nil && x.Betaname != nil {
		return *x.Betaname
	}
	return ""
}

func (x *CMsgClientCheckAppBetaPasswordResponse_BetaPassword) GetBetapassword() string {
	if x != nil && x.Betapassword != nil {
		return *x.Betapassword
	}
	return ""
}

func (x *CMsgClientCheckAppBetaPasswordResponse_BetaPassword) GetBetadescription() string {
	if x != nil && x.Betadescription != nil {
		return *x.Betadescription
	}
	return ""
}

var File_steammessages_clientserver_2_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_2_proto_rawDesc = "" +
	"\n" +
	"\"steammessages_clientserver_2.proto\"S\n" +
	"\x1fCMsgClientGetDepotDecryptionKey\x12\x19\n" +
	"\bdepot_id\x18\x01 \x01(\rR\adepotId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\"\x93\x01\n" +
	"'CMsgClientGetDepotDecryptionKeyResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12\x19\n" +
	"\bdepot_id\x18\x02 \x01(\rR\adepotId\x120\n" +
	"\x14depot_encryption_key\x18\x03 \x01(\fR\x12depotEncryptionKey\"w\n" +
	"\x1eCMsgClientCheckAppBetaPassword\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\"\n" +
	"\fbetapassword\x18\x02 \x01(\tR\fbetapassword\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\x05R\blanguage\"\x9b\x02\n" +
	"&CMsgClientCheckAppBetaPasswordResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12Z\n" +
	"\rbetapasswords\x18\x04 \x03(\v24.CMsgClientCheckAppBetaPasswordResponse.BetaPasswordR\rbetapasswords\x1ax\n" +
	"\fBetaPassword\x12\x1a\n" +
	"\bbetaname\x18\x01 \x01(\tR\bbetaname\x12\"\n" +
	"\fbetapassword\x18\x02 \x01(\tR\fbetapassword\x12(\n" +
	"\x0fbetadescription\x18\x03 \x01(\tR\x0fbetadescriptionB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_2_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_2_proto_rawDescData []byte
)

func file_steammessages_clientserver_2_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_2_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_2_proto_rawDesc), len(file_steammessages_clientserver_2_proto_rawDesc)))
	})
	return file_steammessages_clientserver_2_proto_rawDescData
}

var file_steammessages_clientserver_2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_steammessages_clientserver_2_proto_goTypes = []any{
	(*CMsgClientGetDepotDecryptionKey)(nil),                     // 0: CMsgClientGetDepotDecryptionKey
	(*CMsgClientGetDepotDecryptionKeyResponse)(nil),             // 1: CMsgClientGetDepotDecryptionKeyResponse
	(*CMsgClientCheckAppBetaPassword)(nil),                      // 2: CMsgClientCheckAppBetaPassword
	(*CMsgClientCheckAppBetaPasswordResponse)(nil),              // 3: CMsgClientCheckAppBetaPasswordResponse
	(*CMsgClientCheckAppBetaPasswordResponse_BetaPassword)(nil), // 4: CMsgClientCheckAppBetaPasswordResponse.BetaPassword
}
var file_steammessages_clientserver_2_proto_depIdxs = []int32{
	4, // 0: CMsgClientCheckAppBetaPasswordResponse.betapasswords:type_name -> CMsgClientCheckAppBetaPasswordResponse.BetaPassword
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_2_proto_init() }
func file_steammessages_clientserver_2_proto_init() {
	if File_steammessages_clientserver_2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_2_proto_rawDesc), len(file_steammessages_clientserver_2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_2_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_2_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_2_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_2_proto = out.File
	file_steammessages_clientserver_2_proto_goTypes = nil
	file_steammessages_clientserver_2_proto_depIdxs = nil
}
