// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steammessages_clientserver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientLicenseList struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Eresult       *int32                           `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	Licenses      []*CMsgClientLicenseList_License `protobuf:"bytes,2,rep,name=licenses" json:"licenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientLicenseList fields.
const (
	Default_CMsgClientLicenseList_Eresult = int32(2)
)

func (x *CMsgClientLicenseList) Reset() {
	*x = CMsgClientLicenseList{}
	mi := &file_steammessages_clientserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLicenseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLicenseList) ProtoMessage() {}

func (x *CMsgClientLicenseList) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLicenseList.ProtoReflect.Descriptor instead.
func (*CMsgClientLicenseList) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientLicenseList) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientLicenseList_Eresult
}

func (x *CMsgClientLicenseList) GetLicenses() []*CMsgClientLicenseList_License {
	if x != nil {
		return x.Licenses
	}
	return nil
}

type CMsgClientLicenseList_License struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PackageId           *uint32                `protobuf:"varint,1,opt,name=package_id,json=packageId" json:"package_id,omitempty"`
	TimeCreated         *uint32                `protobuf:"fixed32,2,opt,name=time_created,json=timeCreated" json:"time_created,omitempty"`
	TimeNextProcess     *uint32                `protobuf:"fixed32,3,opt,name=time_next_process,json=timeNextProcess" json:"time_next_process,omitempty"`
	MinuteLimit         *int32                 `protobuf:"varint,4,opt,name=minute_limit,json=minuteLimit" json:"minute_limit,omitempty"`
	MinutesUsed         *int32                 `protobuf:"varint,5,opt,name=minutes_used,json=minutesUsed" json:"minutes_used,omitempty"`
	PaymentMethod       *uint32                `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod" json:"payment_method,omitempty"`
	Flags               *uint32                `protobuf:"varint,7,opt,name=flags" json:"flags,omitempty"`
	PurchaseCountryCode *string                `protobuf:"bytes,8,opt,name=purchase_country_code,json=purchaseCountryCode" json:"purchase_country_code,omitempty"`
	LicenseType         *uint32                `protobuf:"varint,9,opt,name=license_type,json=licenseType" json:"license_type,omitempty"`
	TerritoryCode       *int32                 `protobuf:"varint,10,opt,name=territory_code,json=territoryCode" json:"territory_code,omitempty"`
	ChangeNumber        *int32                 `protobuf:"varint,11,opt,name=change_number,json=changeNumber" json:"change_number,omitempty"`
	OwnerId             *uint32                `protobuf:"varint,12,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	InitialPeriod       *uint32                `protobuf:"varint,13,opt,name=initial_period,json=initialPeriod" json:"initial_period,omitempty"`
	InitialTimeUnit     *uint32                `protobuf:"varint,14,opt,name=initial_time_unit,json=initialTimeUnit" json:"initial_time_unit,omitempty"`
	RenewalPeriod       *uint32                `protobuf:"varint,15,opt,name=renewal_period,json=renewalPeriod" json:"renewal_period,omitempty"`
	RenewalTimeUnit     *uint32                `protobuf:"varint,16,opt,name=renewal_time_unit,json=renewalTimeUnit" json:"renewal_time_unit,omitempty"`
	AccessToken         *uint64                `protobuf:"varint,17,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	MasterPackageId     *uint32                `protobuf:"varint,18,opt,name=master_package_id,json=masterPackageId" json:"master_package_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CMsgClientLicenseList_License) Reset() {
	*x = CMsgClientLicenseList_License{}
	mi := &file_steammessages_clientserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLicenseList_License) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLicenseList_License) ProtoMessage() {}

func (x *CMsgClientLicenseList_License) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLicenseList_License.ProtoReflect.Descriptor instead.
func (*CMsgClientLicenseList_License) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CMsgClientLicenseList_License) GetPackageId() uint32 {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetTimeCreated() uint32 {
	if x != nil && x.TimeCreated != nil {
		return *x.TimeCreated
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetTimeNextProcess() uint32 {
	if x != nil && x.TimeNextProcess != nil {
		return *x.TimeNextProcess
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetMinuteLimit() int32 {
	if x != nil && x.MinuteLimit != nil {
		return *x.MinuteLimit
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetMinutesUsed() int32 {
	if x != nil && x.MinutesUsed != nil {
		return *x.MinutesUsed
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetPaymentMethod() uint32 {
	if x != nil && x.PaymentMethod != nil {
		return *x.PaymentMethod
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetPurchaseCountryCode() string {
	if x != nil && x.PurchaseCountryCode != nil {
		return *x.PurchaseCountryCode
	}
	return ""
}

func (x *CMsgClientLicenseList_License) GetLicenseType() uint32 {
	if x != nil && x.LicenseType != nil {
		return *x.LicenseType
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetTerritoryCode() int32 {
	if x != nil && x.TerritoryCode != nil {
		return *x.TerritoryCode
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetChangeNumber() int32 {
	if x != nil && x.ChangeNumber != nil {
		return *x.ChangeNumber
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetOwnerId() uint32 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetInitialPeriod() uint32 {
	if x != nil && x.InitialPeriod != nil {
		return *x.InitialPeriod
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetInitialTimeUnit() uint32 {
	if x != nil && x.InitialTimeUnit != nil {
		return *x.InitialTimeUnit
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetRenewalPeriod() uint32 {
	if x != nil && x.RenewalPeriod != nil {
		return *x.RenewalPeriod
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetRenewalTimeUnit() uint32 {
	if x != nil && x.RenewalTimeUnit != nil {
		return *x.RenewalTimeUnit
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetAccessToken() uint64 {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return 0
}

func (x *CMsgClientLicenseList_License) GetMasterPackageId() uint32 {
	if x != nil && x.MasterPackageId != nil {
		return *x.MasterPackageId
	}
	return 0
}

var File_steammessages_clientserver_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_proto_rawDesc = "" +
	"\n" +
	" steammessages_clientserver.proto\"\xa0\x06\n" +
	"\x15CMsgClientLicenseList\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12:\n" +
	"\blicenses\x18\x02 \x03(\v2\x1e.CMsgClientLicenseList.LicenseR\blicenses\x1a\xad\x05\n" +
	"\aLicense\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\rR\tpackageId\x12!\n" +
	"\ftime_created\x18\x02 \x01(\aR\vtimeCreated\x12*\n" +
	"\x11time_next_process\x18\x03 \x01(\aR\x0ftimeNextProcess\x12!\n" +
	"\fminute_limit\x18\x04 \x01(\x05R\vminuteLimit\x12!\n" +
	"\fminutes_used\x18\x05 \x01(\x05R\vminutesUsed\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\rR\rpaymentMethod\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x122\n" +
	"\x15purchase_country_code\x18\b \x01(\tR\x13purchaseCountryCode\x12!\n" +
	"\flicense_type\x18\t \x01(\rR\vlicenseType\x12%\n" +
	"\x0eterritory_code\x18\n" +
	" \x01(\x05R\rterritoryCode\x12#\n" +
	"\rchange_number\x18\v \x01(\x05R\fchangeNumber\x12\x19\n" +
	"\bowner_id\x18\f \x01(\rR\aownerId\x12%\n" +
	"\x0einitial_period\x18\r \x01(\rR\rinitialPeriod\x12*\n" +
	"\x11initial_time_unit\x18\x0e \x01(\rR\x0finitialTimeUnit\x12%\n" +
	"\x0erenewal_period\x18\x0f \x01(\rR\rrenewalPeriod\x12*\n" +
	"\x11renewal_time_unit\x18\x10 \x01(\rR\x0frenewalTimeUnit\x12!\n" +
	"\faccess_token\x18\x11 \x01(\x04R\vaccessToken\x12*\n" +
	"\x11master_package_id\x18\x12 \x01(\rR\x0fmasterPackageIdB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_proto_rawDescData []byte
)

func file_steammessages_clientserver_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_proto_rawDesc), len(file_steammessages_clientserver_proto_rawDesc)))
	})
	return file_steammessages_clientserver_proto_rawDescData
}

var file_steammessages_clientserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steammessages_clientserver_proto_goTypes = []any{
	(*CMsgClientLicenseList)(nil),         // 0: CMsgClientLicenseList
	(*CMsgClientLicenseList_License)(nil), // 1: CMsgClientLicenseList.License
}
var file_steammessages_clientserver_proto_depIdxs = []int32{
	1, // 0: CMsgClientLicenseList.licenses:type_name -> CMsgClientLicenseList.License
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_proto_init() }
func file_steammessages_clientserver_proto_init() {
	if File_steammessages_clientserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_proto_rawDesc), len(file_steammessages_clientserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_proto = out.File
	file_steammessages_clientserver_proto_goTypes = nil
	file_steammessages_clientserver_proto_depIdxs = nil
}
